# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'Quiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quiz
  pod 'Alamofire', '~> 4.4’
  pod 'Instructions', '~> 1.0.0'
  

end
